### ISSUE TITLE
Frontier Spirits - Stunts - Duplicate content

### ISSUE THREAD

**Issue by wokste** [amazingrando/fate-srd-content#11]
The page https://fate-srd.com/frontier-spirit/stunts has duplicate text to some other pages. In particular: the text below the headers: Immanence, Spirits and Disasters.

Looking in the markdown, I guess this might be caused by the number of `#` symbols before those main titles. For skills and stunts the headers use `#`. For Immanence, Spirits and Disasters the headers use `##`.

**Comment by amazingrando** [comment]
Thanks for the heads up. I'll fix this.

**Comment by amazingrando** [comment]
@wokste I've fixed this. TY!
